# Generated by Django 3.2.6 on 2021-08-12 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Produkt')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('szt', 'szt')], default='kg', max_length=4, verbose_name='Jednostka')),
                ('pack_size', models.FloatField(verbose_name='Rozmiar opakowania')),
                ('pack_price', models.FloatField(verbose_name='Cena opakowania')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.productcategory', verbose_name='Kategoria')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', to='products.supplier', verbose_name='Dostawca')),
            ],
        ),
    ]
